begin;
create policy product_media_owner on public.product_media for all using(exists(select 1 from products p where p.id=product_id and (p.seller_id=public.current_seller_id() or public.is_admin()))) with check(exists(select 1 from products p where p.id=product_id and (p.seller_id=public.current_seller_id() or public.is_admin())));
create policy product_variants_owner on public.product_variants for all using(exists(select 1 from products p where p.id=product_id and (p.seller_id=public.current_seller_id() or public.is_admin()))) with check(exists(select 1 from products p where p.id=product_id and (p.seller_id=public.current_seller_id() or public.is_admin())));
create policy order_items_seller_read on public.order_items for select using(exists(select 1 from orders o where o.id=order_id and (o.seller_id=public.current_seller_id() or public.is_admin())));
create policy reservations_seller_read on public.inventory_reservations for select using(exists(select 1 from orders o where o.id=order_id and (o.seller_id=public.current_seller_id() or public.is_admin())));
create policy payments_seller_read on public.payments for select using(exists(select 1 from orders o where o.id=order_id and (o.seller_id=public.current_seller_id() or public.is_admin())));
create policy referral_links_seller_read on public.referral_links for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy referral_attribution_seller_read on public.referral_attributions for select using(exists(select 1 from referral_links r where r.id=referral_link_id and (r.seller_id=public.current_seller_id() or public.is_admin())));
create policy rewards_seller_read on public.reward_credits for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy redemption_seller_read on public.reward_redemptions for select using(exists(select 1 from reward_credits r where r.id=reward_credit_id and (r.seller_id=public.current_seller_id() or public.is_admin())));
create policy events_seller_read on public.order_events for select using(exists(select 1 from orders o where o.id=order_id and (o.seller_id=public.current_seller_id() or public.is_admin())));

create or replace function public.get_public_campaign(p_short_code text) returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('id',c.id,'shortCode',c.short_code,'status',c.status,'stockMode',c.stock_mode,'paymentMode',c.payment_mode,'publicPriceKobo',c.public_price_kobo,'referralRewardKobo',c.referral_reward_kobo,'endsAt',c.ends_at,'expectedFulfilmentAt',c.expected_fulfilment_at,'allowRestockInterest',c.allow_restock_interest,'chatFallbackEnabled',c.chat_fallback_enabled,'noindex',c.noindex,'product',jsonb_build_object('id',p.id,'name',p.name,'description',p.description,'category',p.category),'seller',jsonb_build_object('id',s.id,'businessName',s.business_name,'city',s.city,'state',s.state,'logoPath',s.logo_path,'whatsappPhone',s.whatsapp_phone,'shortDescription',s.short_description,'pickupNote',s.pickup_note,'deliveryNote',s.delivery_note,'returnPolicy',s.return_policy,'fulfilmentMethods',s.fulfilment_methods,'paymentVerified',coalesce(a.provider_verified,false)),'media',coalesce((select jsonb_agg(jsonb_build_object('path',m.storage_path,'provider',m.provider,'type',m.media_type,'alt',m.alt_text) order by m.sort_order) from product_media m where m.product_id=p.id),'[]'::jsonb),'variants',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'option1Name',v.option_1_name,'option1Value',v.option_1_value,'option2Name',v.option_2_name,'option2Value',v.option_2_value,'availableQuantity',case when c.stock_mode='fixed' then greatest(0,v.available_quantity-v.reserved_quantity) else null end) order by v.created_at) from product_variants v where v.product_id=p.id and v.is_active),'[]'::jsonb)) from campaigns c join products p on p.id=c.product_id join seller_businesses s on s.id=c.seller_id left join seller_payment_accounts a on a.seller_id=s.id where c.short_code=p_short_code and c.status in('active','sold_out','ended') and s.is_active and s.is_approved$$;
grant execute on function public.get_public_campaign(text) to anon,authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('campaign-media','campaign-media',true,10485760,array['image/jpeg','image/png','image/webp','video/mp4']) on conflict(id) do nothing;
create policy storage_seller_insert on storage.objects for insert to authenticated with check(bucket_id='campaign-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy storage_seller_update on storage.objects for update to authenticated using(bucket_id='campaign-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy storage_seller_delete on storage.objects for delete to authenticated using(bucket_id='campaign-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy storage_public_read on storage.objects for select to anon,authenticated using(bucket_id='campaign-media');
commit;
