begin;
create extension if not exists pgcrypto;

create type public.profile_role as enum ('seller','admin','support');
create type public.campaign_status as enum ('draft','active','paused','sold_out','ended','archived');
create type public.stock_mode as enum ('fixed','on_request','preorder');
create type public.payment_mode as enum ('full','fixed_deposit','percentage_deposit');
create type public.order_status as enum ('payment_pending','partially_paid','paid','confirmed','processing','awaiting_stock','ready_for_pickup','out_for_delivery','delivered','picked_up','cancelled','refund_pending','partially_refunded','refunded','payment_failed','expired');
create type public.payment_status as enum ('initialized','pending','success','failed','abandoned','refund_pending','partially_refunded','refunded','chargeback');
create type public.reward_status as enum ('pending','available','redeemed','expired','reversed','cancelled');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role public.profile_role not null default 'seller',full_name text not null default '',phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.seller_businesses(id uuid primary key default gen_random_uuid(),owner_profile_id uuid not null unique references public.profiles(id),business_name text not null,slug text not null unique,category text not null,logo_path text,whatsapp_phone text not null,email text not null,city text not null,state text not null,short_description text not null default '',pickup_note text not null default '',delivery_note text not null default '',return_policy text not null default '',fulfilment_methods text[] not null default '{}',terms_accepted_at timestamptz,is_active boolean not null default true,is_approved boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.seller_payment_accounts(id uuid primary key default gen_random_uuid(),seller_id uuid not null unique references public.seller_businesses(id),provider text not null default 'paystack',bank_code text,account_number_last4 text check(account_number_last4 is null or account_number_last4 ~ '^[0-9]{4}$'),account_name text,subaccount_code text,provider_verified boolean not null default false,status text not null default 'pending' check(status in('pending','active','rejected','disabled')),metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.seller_businesses(id),name text not null,description text not null default '',category text not null,status text not null default 'draft' check(status in('draft','active','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_media(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,storage_path text not null,provider text not null default 'supabase' check(provider in('supabase','cloudinary')),media_type text not null check(media_type in('image','video')),sort_order integer not null default 0,alt_text text not null,consent_confirmed boolean not null default false,created_at timestamptz not null default now());
create table public.product_variants(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,sku text,option_1_name text,option_1_value text,option_2_name text,option_2_value text,available_quantity integer check(available_quantity is null or available_quantity>=0),reserved_quantity integer not null default 0 check(reserved_quantity>=0),seller_take_home_override_kobo bigint check(seller_take_home_override_kobo is null or seller_take_home_override_kobo>=0),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(reserved_quantity<=coalesce(available_quantity,reserved_quantity)));
create table public.campaigns(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.seller_businesses(id),product_id uuid not null references public.products(id),short_code text not null unique,status public.campaign_status not null default 'draft',stock_mode public.stock_mode not null,payment_mode public.payment_mode not null default 'full',deposit_value integer check(deposit_value is null or deposit_value>0),seller_minimum_take_home_kobo bigint not null check(seller_minimum_take_home_kobo>0),seller_purchase_cost_kobo bigint check(seller_purchase_cost_kobo is null or seller_purchase_cost_kobo>=0),referral_reward_kobo bigint not null default 0 check(referral_reward_kobo>=0),public_price_kobo bigint not null check(public_price_kobo>0),reservation_minutes integer not null default 30 check(reservation_minutes between 5 and 10080),starts_at timestamptz not null default now(),ends_at timestamptz,expected_fulfilment_at timestamptz,allow_restock_interest boolean not null default true,allow_substitution boolean not null default false,chat_fallback_enabled boolean not null default true,noindex boolean not null default false,pricing_snapshot jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or ends_at>starts_at));
create table public.customers(id uuid primary key default gen_random_uuid(),full_name text not null,normalized_phone text not null,email text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(normalized_phone,email));
create table public.seller_customers(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.seller_businesses(id),customer_id uuid not null references public.customers(id),first_order_at timestamptz not null,last_order_at timestamptz not null,completed_order_count integer not null default 0,total_paid_kobo bigint not null default 0,notes text,unique(seller_id,customer_id));
create table public.orders(id uuid primary key default gen_random_uuid(),public_token_hash text not null unique,public_reference text not null unique,seller_id uuid not null references public.seller_businesses(id),customer_id uuid not null references public.customers(id),campaign_id uuid not null references public.campaigns(id),status public.order_status not null default 'payment_pending',fulfilment_method text not null check(fulfilment_method in('pickup','seller_delivery','dispatch','waybill','meet_up','other')),delivery_address text,delivery_fee_kobo bigint not null default 0,item_subtotal_kobo bigint not null,discount_kobo bigint not null default 0,total_due_kobo bigint not null,total_paid_kobo bigint not null default 0,seller_target_kobo bigint not null,platform_target_kobo bigint not null,reward_funding_kobo bigint not null default 0,paystack_fee_estimate_kobo bigint not null,currency text not null default 'NGN' check(currency='NGN'),buyer_note text,seller_private_note text,seller_buyer_message text,referred_by_referral_id uuid,reward_redemption_id uuid,pricing_snapshot jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(total_due_kobo>=0 and total_paid_kobo>=0));
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid not null references public.products(id),variant_id uuid references public.product_variants(id),product_name_snapshot text not null,variant_snapshot jsonb not null default '{}',quantity integer not null check(quantity>0),unit_public_price_kobo bigint not null check(unit_public_price_kobo>=0),unit_seller_target_kobo bigint not null check(unit_seller_target_kobo>=0),created_at timestamptz not null default now());
create table public.inventory_reservations(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),variant_id uuid not null references public.product_variants(id),quantity integer not null check(quantity>0),status text not null default 'active' check(status in('active','converted','released','expired')),expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),provider text not null default 'paystack',provider_reference text not null unique,status public.payment_status not null default 'initialized',amount_kobo bigint not null check(amount_kobo>0),currency text not null default 'NGN' check(currency='NGN'),payment_type text not null check(payment_type in('deposit','balance','full')),authorization_url text,provider_transaction_id text,provider_channel text,provider_paid_at timestamptz,raw_verified_summary jsonb,processed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_webhook_events(id uuid primary key default gen_random_uuid(),provider text not null,event_key text not null unique,event_type text not null,signature_valid boolean not null,payload jsonb not null,processing_status text not null default 'received' check(processing_status in('received','processed','ignored','failed')),error_message text,received_at timestamptz not null default now(),processed_at timestamptz);
commit;
