begin;
create table public.referral_links(id uuid primary key default gen_random_uuid(),public_code text not null unique,seller_id uuid not null references public.seller_businesses(id),campaign_id uuid not null references public.campaigns(id),referrer_customer_id uuid not null references public.customers(id),originating_order_id uuid not null references public.orders(id),status text not null default 'active' check(status in('active','expired','blocked')),attribution_expires_at timestamptz not null,created_at timestamptz not null default now());
alter table public.orders add constraint orders_referral_fk foreign key(referred_by_referral_id) references public.referral_links(id);
create table public.referral_attributions(id uuid primary key default gen_random_uuid(),referral_link_id uuid not null references public.referral_links(id),referred_customer_id uuid references public.customers(id),order_id uuid unique references public.orders(id),status text not null default 'visited' check(status in('visited','checkout_started','paid','qualified','rejected','reversed')),first_seen_at timestamptz not null default now(),paid_at timestamptz,qualified_at timestamptz,fraud_reason text,signals jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.reward_credits(id uuid primary key default gen_random_uuid(),public_code_hash text not null unique,seller_id uuid not null references public.seller_businesses(id),owner_customer_id uuid not null references public.customers(id),source_order_id uuid not null references public.orders(id),source_referral_attribution_id uuid not null unique references public.referral_attributions(id),amount_kobo bigint not null check(amount_kobo>0),status public.reward_status not null default 'pending',available_at timestamptz,expires_at timestamptz,redeemed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.reward_redemptions(id uuid primary key default gen_random_uuid(),reward_credit_id uuid not null unique references public.reward_credits(id),order_id uuid not null unique references public.orders(id),amount_kobo bigint not null check(amount_kobo>0),created_at timestamptz not null default now());
alter table public.orders add constraint orders_redemption_fk foreign key(reward_redemption_id) references public.reward_redemptions(id);
create table public.order_events(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),event_type text not null,from_status text,to_status text,actor_type text not null check(actor_type in('system','buyer','seller','admin','paystack')),actor_id uuid,public_message text,private_metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.restock_interests(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.seller_businesses(id),campaign_id uuid not null references public.campaigns(id),customer_id uuid not null references public.customers(id),variant_request jsonb not null,quantity integer not null check(quantity>0),maximum_price_kobo bigint,status text not null default 'waiting' check(status in('waiting','contacted','converted','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.substitution_offers(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),seller_id uuid not null references public.seller_businesses(id),offer_type text not null check(offer_type in('colour','size','similar_product','price_adjustment','refund')),details jsonb not null,price_difference_kobo bigint not null default 0,status text not null default 'pending' check(status in('pending','accepted','rejected','expired','withdrawn')),expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.fee_configs(id uuid primary key default gen_random_uuid(),name text not null,currency text not null default 'NGN',paystack_percent_basis_points integer not null,paystack_fixed_kobo bigint not null,paystack_fixed_threshold_kobo bigint not null,paystack_cap_kobo bigint not null,platform_percent_basis_points integer not null,platform_flat_kobo bigint not null,platform_min_kobo bigint not null,platform_max_kobo bigint,pricing_safety_buffer_kobo bigint not null default 0,rounding_increment_kobo bigint not null,reward_min_kobo bigint not null,reward_max_kobo bigint not null,reward_max_percent_basis_points integer not null,effective_from timestamptz not null,effective_to timestamptz,is_active boolean not null default true,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),check(rounding_increment_kobo>0 and reward_max_kobo>=reward_min_kobo));
create unique index one_active_fee_config on public.fee_configs(currency) where is_active;
create table public.audit_logs(id uuid primary key default gen_random_uuid(),actor_profile_id uuid references public.profiles(id),action text not null,resource_type text not null,resource_id uuid,before_data jsonb,after_data jsonb,ip_hash text,user_agent text,created_at timestamptz not null default now());
create table public.feature_flags(key text primary key,enabled boolean not null,configuration jsonb not null default '{}',updated_by uuid references public.profiles(id),updated_at timestamptz not null default now());
create table public.analytics_events(id uuid primary key default gen_random_uuid(),event_name text not null,seller_id uuid references public.seller_businesses(id),campaign_id uuid references public.campaigns(id),order_id uuid references public.orders(id),anonymous_id_hash text,properties jsonb not null default '{}',created_at timestamptz not null default now());
create table public.seller_invites(id uuid primary key default gen_random_uuid(),email text not null,token_hash text not null unique,status text not null default 'pending' check(status in('pending','accepted','expired','revoked')),expires_at timestamptz not null,invited_by uuid references public.profiles(id),accepted_by uuid references public.profiles(id),created_at timestamptz not null default now());

create or replace function public.current_seller_id() returns uuid language sql stable security definer set search_path=public as $$select id from seller_businesses where owner_profile_id=auth.uid()$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role in('admin','support'))$$;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now(); return new; end$$;
do $$declare t text; begin foreach t in array array['profiles','seller_businesses','seller_payment_accounts','products','product_variants','campaigns','customers','orders','inventory_reservations','payments','referral_attributions','reward_credits','restock_interests','substitution_offers'] loop execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end loop; end$$;

create or replace function public.reserve_variant(p_order uuid,p_variant uuid,p_quantity integer,p_expires timestamptz) returns uuid language plpgsql security definer set search_path=public as $$declare v product_variants%rowtype; r uuid; begin if p_quantity<=0 then raise exception 'invalid_quantity'; end if; select * into v from product_variants where id=p_variant for update; if not found or not v.is_active then raise exception 'variant_unavailable'; end if; if v.available_quantity is not null and v.available_quantity-v.reserved_quantity<p_quantity then raise exception 'insufficient_stock'; end if; update product_variants set reserved_quantity=reserved_quantity+p_quantity where id=p_variant; insert into inventory_reservations(order_id,variant_id,quantity,expires_at) values(p_order,p_variant,p_quantity,p_expires) returning id into r; return r; end$$;
create or replace function public.release_expired_reservations() returns integer language plpgsql security definer set search_path=public as $$declare n integer; begin with expired as(update inventory_reservations set status='expired',updated_at=now() where status='active' and expires_at<=now() returning variant_id,quantity), totals as(select variant_id,sum(quantity)::integer quantity from expired group by variant_id) update product_variants v set reserved_quantity=greatest(0,v.reserved_quantity-t.quantity) from totals t where v.id=t.variant_id; get diagnostics n=row_count; return n; end$$;
create or replace function public.convert_payment_success(p_reference text,p_provider_id text,p_channel text,p_paid_at timestamptz,p_summary jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare p payments%rowtype;o orders%rowtype;begin select * into p from payments where provider_reference=p_reference for update;if not found then raise exception 'payment_not_found';end if;if p.status='success' then return p.order_id;end if;select * into o from orders where id=p.order_id for update;if p.currency<>'NGN' or p.amount_kobo<=0 then raise exception 'invalid_payment';end if;update payments set status='success',provider_transaction_id=p_provider_id,provider_channel=p_channel,provider_paid_at=p_paid_at,raw_verified_summary=p_summary,processed_at=now() where id=p.id;update orders set total_paid_kobo=least(total_due_kobo,total_paid_kobo+p.amount_kobo),status=case when total_paid_kobo+p.amount_kobo>=total_due_kobo then 'paid'::order_status else 'partially_paid'::order_status end where id=o.id;update inventory_reservations set status='converted' where order_id=o.id and status='active';update product_variants v set available_quantity=case when v.available_quantity is null then null else v.available_quantity-r.quantity end,reserved_quantity=greatest(0,v.reserved_quantity-r.quantity) from inventory_reservations r where r.order_id=o.id and r.variant_id=v.id and r.status='converted';insert into order_events(order_id,event_type,from_status,to_status,actor_type,public_message) values(o.id,'payment_verified',o.status::text,case when o.total_paid_kobo+p.amount_kobo>=o.total_due_kobo then 'paid' else 'partially_paid' end,'paystack','Payment confirmed');return o.id;end$$;

alter table public.profiles enable row level security;alter table public.seller_businesses enable row level security;alter table public.seller_payment_accounts enable row level security;alter table public.products enable row level security;alter table public.product_media enable row level security;alter table public.product_variants enable row level security;alter table public.campaigns enable row level security;alter table public.customers enable row level security;alter table public.seller_customers enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.inventory_reservations enable row level security;alter table public.payments enable row level security;alter table public.payment_webhook_events enable row level security;alter table public.referral_links enable row level security;alter table public.referral_attributions enable row level security;alter table public.reward_credits enable row level security;alter table public.reward_redemptions enable row level security;alter table public.order_events enable row level security;alter table public.restock_interests enable row level security;alter table public.substitution_offers enable row level security;alter table public.fee_configs enable row level security;alter table public.audit_logs enable row level security;alter table public.feature_flags enable row level security;alter table public.analytics_events enable row level security;alter table public.seller_invites enable row level security;

create policy profile_self on public.profiles for select using(id=auth.uid() or public.is_admin());create policy profile_update_self on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy business_owner_select on public.seller_businesses for select using(owner_profile_id=auth.uid() or public.is_admin());create policy business_owner_update on public.seller_businesses for update using(owner_profile_id=auth.uid()) with check(owner_profile_id=auth.uid());
create policy seller_payment_owner on public.seller_payment_accounts for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_products_all on public.products for all using(seller_id=public.current_seller_id() or public.is_admin()) with check(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_campaigns_all on public.campaigns for all using(seller_id=public.current_seller_id() or public.is_admin()) with check(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_orders_select on public.orders for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_customers_select on public.seller_customers for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_restock_select on public.restock_interests for select using(seller_id=public.current_seller_id() or public.is_admin());
create policy seller_substitution_all on public.substitution_offers for all using(seller_id=public.current_seller_id() or public.is_admin()) with check(seller_id=public.current_seller_id() or public.is_admin());
create policy admin_fees on public.fee_configs for all using(public.is_admin()) with check(public.is_admin());create policy admin_flags on public.feature_flags for all using(public.is_admin()) with check(public.is_admin());create policy admin_audit_read on public.audit_logs for select using(public.is_admin());
commit;
